# Generated by Django 5.2.1 on 2025-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Out for delivery'), (1, 'Delivered')], db_index=True, default=0),
        ),
    ]
