# Generated by Django 5.2.1 on 2025-05-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Out for delivery'), (1, 'Delivered')], db_index=True, default='Unassigned'),
        ),
    ]
